namespace myproject.Migrations
{
    using myproject.Models;
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<myproject.Models.ApplicationDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(myproject.Models.ApplicationDbContext context)
        {
            var products = new List<Product>
            {
                new Product{productname="Si Cẩm Thạch", category=Category.product, price=80000 , description="", image="../../images/products/pd_1.png", clade_hashtag="Tracheophytes Angiosperms Eudicots", family_hasttag="Strelitziaceae", difficulty_hashtag="easy"},
                new Product{productname="Trầu Bà Vàng Mini", category=Category.product, price=70000 , description="", image="../../images/products/pd_2.png", clade_hashtag="Monocots Angiosperms Eudicots", family_hasttag="Moraceae", difficulty_hashtag="standard"},
                new Product{productname="Đuôi công lá  nhỏ", category=Category.product, price=80000 , description="", image="../../images/products/pd_3.png", clade_hashtag="Strelitziaceae Monocots Eudicots", family_hasttag="Malvaceae", difficulty_hashtag="expert"},
                new Product{productname="Cây giữ tiền", category=Category.product, price=130000 , description="", image="../../images/products/pd_4.png", clade_hashtag="Commelinids Angiosperms Rosids", family_hasttag="Moraceae", difficulty_hashtag="standard"},
                new Product{productname="Vạn Niên Tùng", category=Category.product, price=80000 , description="", image="../../images/products/pd_5.png", clade_hashtag="Tracheophytes Rosids Eudicots", family_hasttag="Strelitziaceae", difficulty_hashtag="expert"},
                new Product{productname="Xương rồng Thanh Sơn", category=Category.product, price=130000 , description="", image="../../images/products/pd_6.png", clade_hashtag="Tracheophytes Rosids Eudicots", family_hasttag="Malvaceae", difficulty_hashtag="standard"},
                new Product{productname="Trường Sinh", category=Category.product, price=80000 , description="", image="../../images/products/pd_7.png", clade_hashtag="Tracheophytes Strelitziaceae Rosids", family_hasttag="Moraceae", difficulty_hashtag="easy"},
                new Product{productname="Cỏ Gương", category=Category.product, price=50000 , description="", image="../../images/products/pd_8.png", clade_hashtag="Monocots Angiosperms Rosids", family_hasttag="Strelitziaceae", difficulty_hashtag="easy"},
                new Product{productname="Lan Ý", category=Category.product, price=130000 , description="", image="../../images/products/pd_9.png", clade_hashtag="Tracheophytes Strelitziaceae Eudicots", family_hasttag="Moraceae", difficulty_hashtag="standard"},
                new Product{productname="Ngũ Gia Bì", category=Category.product, price=70000 , description="", image="../../images/products/pd_10.png", clade_hashtag="Angiosperms Strelitziaceae Eudicots", family_hasttag="Asparagaceae", difficulty_hashtag="expert"},
                new Product{productname="Đuôi Công", category=Category.product, price=170000 , description="", image="../../images/products/pd_11.png", clade_hashtag="Commelinids Angiosperms Rosids", family_hasttag="Moraceae", difficulty_hashtag="easy"},
                new Product{productname="Trầu Bà Lỗ", category=Category.product, price=170000 , description="", image="../../images/products/pd_12.png", clade_hashtag="Commelinids Angiosperms Eudicots", family_hasttag="Strelitziaceae", difficulty_hashtag="expert"},
                new Product{productname="Trầu Bà Thanh Xuân", category=Category.product, price=350000 , description="", image="../../images/products/pd_13.png", clade_hashtag="Tracheophytes Angiosperms Rosids", family_hasttag="Asparagaceae", difficulty_hashtag="standard"},
                new Product{productname="Thiết Mộc Lan", category=Category.product, price=150000 , description="", image="../../images/products/pd_14.png", clade_hashtag="Tracheophytes Angiosperms Eudicots", family_hasttag="Malvaceae", difficulty_hashtag="easy"},
                new Product{productname="Bàng Singapore", category=Category.product, price=350000 , description="", image="../../images/products/pd_15.png", clade_hashtag="Commelinids Angiosperms Monocots", family_hasttag="Asparagaceae", difficulty_hashtag="standard"},
                new Product{productname="Đại Phú", category=Category.product, price=450000 , description="", image="../../images/products/pd_16.png", clade_hashtag="Rosids Commelinids Eudicots", family_hasttag="Malvaceae", difficulty_hashtag="expert"}
            };
            products.ForEach(s => context.Products.Add(s));
            context.SaveChanges();

            var furniture = new List<Product>
            {
                new Product{productname="Kệ chữ A bốn tầng", category=Category.furniture, price=1350000 , description="Kệ chữ A bốn tầng được thiết kế đặc biệt thích hợp dùng bày trí ngoài vườn, cùng các loại cây xanh từ cây dáng rũ, cây thân thảo, đến thân bụi, xương rồng, v.v. Ngoài ra, bạn có thể sắp xếp thêm các vật dụng làm vườn như bình tưới nước.", image="../../images/furniture/f_1.png"},
                new Product{productname="Kệ chữ A bốn tầng đa năng", category=Category.furniture, price=3000000 , description="Kệ chữ A bốn tầng lớn đa dụng hơn và có thể bày trí cả trong nhà và ngoài vườn. Đặc biệt, nếu bạn vừa muốn trang trí các vật dụng như sách hay giỏ cho kệ vừa muốn có thể thường xuyên tưới nước cho các chậu cây của mình, thì chiếc hộc của Kệ sẽ là người bạn đồng hành hoàn hảo đó.", image="../../images/furniture/f_2.png"},
                new Product{productname="Kệ xe đẩy Gỗ", category=Category.furniture, price=2500000 , description="Kệ xe đẩy gỗ được ưu ái là thiết kế mới - mang tính tối ưu, đa nhiệm và năng động nhất trong các anh em nhà kệ, với hai tầng kệ đựng đồ cùng 2 bánh xe trước và 2 bánh xe sau có khoá. Chỉ với hai tầng chứa đồ, bạn sẽ khá ưng bụng với người bạn 4-bánh-xe linh hoạt, tiện nghi này.", image="../../images/furniture/f_3.png"},
                new Product{productname="Đôn Gỗ x Sọt Tre", category=Category.furniture, price=400000 , description="Ở Yên, thiết kế chân gỗ - 3 đế trụ được dành riêng cho các em giỏ mây, sọt tre, phù hợp trang trí các góc nhà, gian phòng cần thanh lọc không khí. Sọt tre với chiếc dáng bầu được đan tỉ mỉ, xen lẫn tạo nên một vẻ đẹp cực kỳ thu hút nhưng không kém phần sang trọng, tối giản với tông màu vàng ngà.", image="../../images/furniture/f_4.png"},
                new Product{productname="Kệ chữ A 4 tầng có tủ", category=Category.furniture, price=1350000 , description="Kệ chữ A bốn tầng được thiết kế đặc biệt thích hợp dùng bày trí ngoài vườn, cùng các loại cây xanh từ cây dáng rũ, cây thân thảo, đến thân bụi, xương rồng, v.v. Ngoài ra, bạn có thể sắp xếp thêm các vật dụng làm vườn như bình tưới nước.", image="../../images/furniture/f_5.png"},
                new Product{productname="Kệ chữ A 4 tầng to", category=Category.furniture, price=3000000 , description="Kệ chữ A bốn tầng lớn đa dụng hơn và có thể bày trí cả trong nhà và ngoài vườn. Đặc biệt, nếu bạn vừa muốn trang trí các vật dụng như sách hay giỏ cho kệ vừa muốn có thể thường xuyên tưới nước cho các chậu cây của mình, thì chiếc hộc của Kệ sẽ là người bạn đồng hành hoàn hảo đó.", image="../../images/furniture/f_6.png"},
                new Product{productname="Kệ 2 tầng", category=Category.furniture, price=2500000 , description="Kệ xe đẩy gỗ được ưu ái là thiết kế mới - mang tính tối ưu, đa nhiệm và năng động nhất trong các anh em nhà kệ, với hai tầng kệ đựng đồ cùng 2 bánh xe trước và 2 bánh xe sau có khoá. Chỉ với hai tầng chứa đồ, bạn sẽ khá ưng bụng với người bạn 4-bánh-xe linh hoạt, tiện nghi này.", image="../../images/furniture/f_7.png"},
                new Product{productname="Kệ 2 tầng có bánh lăn", category=Category.furniture, price=400000 , description="Ở Yên, thiết kế chân gỗ - 3 đế trụ được dành riêng cho các em giỏ mây, sọt tre, phù hợp trang trí các góc nhà, gian phòng cần thanh lọc không khí. Sọt tre với chiếc dáng bầu được đan tỉ mỉ, xen lẫn tạo nên một vẻ đẹp cực kỳ thu hút nhưng không kém phần sang trọng, tối giản với tông màu vàng ngà.", image="../../images/furniture/f_8.png"},
                new Product{productname="Kệ đứng chữ A", category=Category.furniture, price=1350000 , description="Kệ chữ A bốn tầng được thiết kế đặc biệt thích hợp dùng bày trí ngoài vườn, cùng các loại cây xanh từ cây dáng rũ, cây thân thảo, đến thân bụi, xương rồng, v.v. Ngoài ra, bạn có thể sắp xếp thêm các vật dụng làm vườn như bình tưới nước.", image="../../images/furniture/f_9.png"},
                new Product{productname="Kệ đứng chữ A kèm cây", category=Category.furniture, price=3000000 , description="Kệ chữ A bốn tầng lớn đa dụng hơn và có thể bày trí cả trong nhà và ngoài vườn. Đặc biệt, nếu bạn vừa muốn trang trí các vật dụng như sách hay giỏ cho kệ vừa muốn có thể thường xuyên tưới nước cho các chậu cây của mình, thì chiếc hộc của Kệ sẽ là người bạn đồng hành hoàn hảo đó.", image="../../images/furniture/f_10.png"},
            };
            furniture.ForEach(s => context.Products.Add(s));
            context.SaveChanges();

            var workshop = new List<Product>
            {
                new Product{productname="Workshop Terrarium Size L", category=Category.workshop, price=1000000 , description="", image="../../images/workshops/ws_1.jpg"},
                new Product{productname="Workshop Terrarium Size M", category=Category.workshop, price=500000 , description="", image="../../images/workshops/ws_2.jpg"},
                new Product{productname="Workshop Kokedama", category=Category.workshop, price=350000 , description="", image="../../images/workshops/ws_3.jpg"},
            };
            workshop.ForEach(s => context.Products.Add(s));
            context.SaveChanges();
            var guide = new List<Guide>
            {
                new Guide{GuideTitle="", GuideDescription="We’re just as disappointed this isn’t the Sims’ money tree, but IRL the money tree is a symbol of positive energy, luck, and prosperity. Who doesn’t want that?", Guide_Light="Bright, indirect lights. Thrives in fluorescent lighting (perfect for apartment living).", Guide_Water="Water when the soil is almost completely dry at top", Guide_Petfriendly="Yes", Guide_Level="Beginner to intermediate", Guide_Tip="Wipe any accumulated dust off the leaves", clade_hashtag="Tracheophytes Angiosperms Eudicots", difficulty_hashtag="easy", family_hasttag="Strelitziaceae Moraceae"},
                new Guide{GuideTitle="", GuideDescription="The fiddle leaf fig is an instagram plant fave and great decor for a boring corner. With its glossy, dark leaves, it acts as an extra statement piece to any room.", Guide_Light="Place it in a well-lit spot where it will receive indirect lighting all day long", Guide_Water="Keep the soil moist, but let at least 1 inch of soil dry out before watering again. During the summer it requires more frequent watering", Guide_Petfriendly="No. It’s toxic if cats or dogs ingest it", Guide_Level="Intermediate. The fiddle leaf fig can be quite the diva", Guide_Tip="This plant loves it some humidity so giving it a good mist keeps it happy", clade_hashtag="Tracheophytes Angiosperms Rosids", difficulty_hashtag="standard", family_hasttag="Strelitziaceae Malvaceae"},
                new Guide{GuideTitle="", GuideDescription="The rubber plant is the less finicky sister of the fiddle leaf that you can tame down to 1-foot tall with pruning. It’s deep, green leaves have a rubbery look that is v bold.", Guide_Light="Give this one bright light, but not direct sunlight", Guide_Water="Try watering it about 1 to 2 times a week (yellow leaves = lay off the water). Let the soil dry on top before watering. Make sure to really keep it moist during the summer, which is when it thrives", Guide_Petfriendly="No. It’s poisonous to pets and humans if eaten", Guide_Level="Beginner", Guide_Tip="If you want new leaf growth after leaves have fallen off, cut a small notch in the node where the leaf fell from", clade_hashtag="Tracheophytes Angiosperms Monocots", difficulty_hashtag="expert", family_hasttag="Asparagaceae Moraceae"},
                new Guide{GuideTitle="", GuideDescription="Another tropical fave, the giant bird of paradise plant has tall stems with banana-like leaves. Flowers can develop, but unfortunately they don’t typically appear indoors.", Guide_Light="It enjoys bright, indirect light. Too much direct light can damage leaves and flowers", Guide_Water="Keep soil moist. In colder months, let the soil dry out more before watering", Guide_Petfriendly="No. This plant is toxic to felines and fido", Guide_Level="Beginner", Guide_Tip="Rotate the plant every so often for optimal growth", clade_hashtag="Tracheophytes Angiosperms Commelinids", difficulty_hashtag="standard", family_hasttag="Strelitziaceae Moraceae"},
                new Guide{GuideTitle="", GuideDescription="We love a good low-maintenance plant, and one of the most popular is the Madagascar dragon tree. This plant has great architectural leaves, curving as it grows for a tropical look. Bust out the kiddie pool and mojitos, who needs a real vacation, anyway.", Guide_Light="Set this on in moderate to bright, indirect light", Guide_Water="Water when soil dries out at top. Leaves will turn black if overwatered", Guide_Petfriendly="No. Sap is toxic to animals", Guide_Level="Beginner to intermediate", Guide_Tip="Overwatering this plant can be tempting, but just let it live", clade_hashtag="Angiosperms Eudicots Rosids", difficulty_hashtag="expert", family_hasttag="Strelitziaceae Moraceae"},
                new Guide{GuideTitle="", GuideDescription="The dracaena corn plant is easy to maintain, and with its yellow and green leaves, it can brighten up your living space. This plant also made the list of air-filtering plants from the NASA clean air study.", Guide_Light="It loves bright, indirect light, and fluorescent lighting. Avoid direct sunlight", Guide_Water="Water when soil becomes slightly dry at the top. Be sure not to overwater because the tips will turn brown", Guide_Petfriendly="No. Toxic to animals", Guide_Level="Beginner", Guide_Tip="Don’t use leaf shine on corn plants. They’re not a fan", clade_hashtag="Angiosperms Eudicots Monocots", difficulty_hashtag="standard", family_hasttag="Strelitziaceae Asparagaceae"},
                new Guide{GuideTitle="", GuideDescription="We love some tropical vibes. The bamboo palm is one of the easier palms to take care of, and adapts easily to its environment. So if sunlight is an issue, we’ve got you. Plus, add it to the list of air purifying plants.", Guide_Light="This plant likes all lighting except direct sunlight", Guide_Water="eep soil moist, but be sure to have drainage for the plant. It doesn’t like too much water", Guide_Petfriendly="Yes", Guide_Level="Beginner", Guide_Tip="Overwatering is the bamboo palm killer. It hates soggy soil. If you have a history neglecting plants, the bamboo palm is definitely for you", clade_hashtag="Angiosperms Eudicots Commelinids", difficulty_hashtag="expert", family_hasttag="Moraceae Asparagaceae"},
                new Guide{GuideTitle="", GuideDescription="This is a go-to gift for birthdays, weddings, and anniversaries due to its heart-shaped leaves (what better way to show your love than a plant!). It loves to climb and makes a great hanging plant, plus it’s also very hard to kill. New plant parents rejoice!", Guide_Light="It likes medium light, but can tolerate bright, indirect light", Guide_Water="Keep soil moist at all times", Guide_Petfriendly="No. This plant is poisonous to cats and dogs", Guide_Level="Beginner", Guide_Tip="You can keep this plant small if you don’t have the space to let it grow. Just trim it down", clade_hashtag="Eudicots Monocots Commelinids", difficulty_hashtag="easy", family_hasttag="Strelitziaceae Moraceae"},
                new Guide{GuideTitle="", GuideDescription="Also known as the Swiss cheese plant for its holes, the Monstera is iconic from many 70’s photographs, album covers, or advertisements. With its aerial roots, the Monsteraloves to climb and spread out. Be sure to place it somewhere where it can take up some room. Buyer beware: This plant is pricey and will set you back a few bucks.", Guide_Light="Give it bright, indirect light. Avoid placing it in direct sunlight", Guide_Water="Water whenever the soil starts to dry out", Guide_Petfriendly="No. This plant is poisonous", Guide_Level="Beginner", Guide_Tip="Occasionally wipe leaves off for any dust particles", clade_hashtag="Tracheophytes Commelinids Eudicots", difficulty_hashtag="easy", family_hasttag="Strelitziaceae Asparagaceae"},
                new Guide{GuideTitle="", GuideDescription="Need some color to brighten up a drab room? The polka dot plant comes in a variety or colors, but is often known for its pink spots.", Guide_Light="Indirect sunlight is best, but direct sunlight during the day works if the plant doesn’t have much color yet", Guide_Water="Well-drained and moist soil", Guide_Petfriendly="Yes", Guide_Level="Beginner to intermediate", Guide_Tip="They aren’t too difficult to grow, but they do have a shorter lifespan compared to most plants. Keeping this plant indoors actually prolongs its life", clade_hashtag="Rosids Monocots Commelinids", difficulty_hashtag="easy", family_hasttag="Malvaceae Asparagaceae"},
            };
            guide.ForEach(s => context.Guides.Add(s));
            context.SaveChanges();
            var roles = new List<ApplicationRole>
            {
                new ApplicationRole{ Id = "39b42767-b4a1-4b66-8f88-18821673bf23", Name ="Admin"},
                new ApplicationRole{ Id = "1283913f-asda-eeas-xxx3-dadasdasd333", Name ="Product & Order Manager"},
                new ApplicationRole{ Id = "mooo3llj-bmol-dasd-asdd-dasdasd33333", Name ="Event Manager"},
            };
            roles.ForEach(s => context.Roles.Add(s));
            context.SaveChanges();
        }
    }
}